#spring:
#  jpa:
#    database: h2
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: false
#  datasource:
#    url: jdbc:h2:mem:portfolio
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Pyeong9312
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver